name: Go

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: |
        ls -al
        cd src
        echo "<- Let's try this test ->"
        GOARCH=amd64 GOOS=linux go build -o bin/main .
        ls -la bin/

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: main-artifact
        path: |
          src/bin/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Download math result for job 1
        uses: actions/download-artifact@v2
        with:
          name: main-artifact
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-2
#        run: |
#          - echo $TEST_SECRET | sed -e 's/\(.\)/\1 /g'

      - shell: bash
        env:
#          SUPER_SECRET: ${{ secrets.TEST }}}
#          SNS_RESOURCE_ID: ${{ secrets.SNS_RESOURCE_ID }}
#          KMS_RESOURCE_NAME: ${{ secrets.KMS_RESOURCE_NAME }}
          TEST_SECRET: ${{ secrets.TEST }}
          #TEST_OLLA: ${{ secrets.TEST_OLLA }}
        run: |
          echo $TEST_SECRET | sed -e 's/\(.\)/\1 /g'
          docker ps


#          cd scripts
#          ls -al
#          ./compress-main-file.sh
#          cd ../deployment
#          ls -al